name: Deploy Go Web App

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1 # Adjust the Go version as needed

    - name: Build
      run: go build -o app main.go

    - name: Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Use the secret you added for your SSH private key
      run: |
        # Transfer the binary to your EC2 instance using SCP or any other method
        scp -i $SSH_PRIVATE_KEY app ec2-user@3.89.221.142:/home/ec2-user/my-app
        
        # Connect to your EC2 instance and restart your Go application
        ssh -i $SSH_PRIVATE_KEY ec2-user@3.89.221.142 "cd 3.89.221.142 && ./appi"
