name: Go CI Workflow

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x  # Use the desired Go version

      - name: Build
        run: go build -o myapp

      - name: Test
        run: go test ./...

